config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => '/res'

  root to: redirect('courses')

  resources :courses, only: [:new, :create, :index]

  get '(courses/:course_uuid)/lessons', to: 'lessons#index', as: 'course_lessons'
  get '(courses/:course_uuid)/lessons/new', to: 'lessons#new', as: 'new_course_lesson'
  post '(courses/:course_uuid)/lessons', to: 'lessons#create'

  resources :lessons, only: [:show] do
    put 'add_downloadable_material', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_breadcrumb 'courses', :root_path

  def event_store
    Rails.configuration.event_store
  end

  def command_bus
    Rails.configuration.command_bus
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @create_course_cmd = CourseManagement::DraftCourse.new(course_uuid: SecureRandom.uuid)
  end

  def create
    @create_course_cmd = CourseManagement::DraftCourse.new(course_params)
    command_bus.(@create_course_cmd)
    if @create_course_cmd.errors.any?
      render 'new'
    else
      redirect_to courses_path, notice: 'Course was successfully created.'
    end
  end

  private

  def course_params
    params.require(:course).permit(:course_uuid, :name, :description)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_course, except: :show
  before_action :set_lesson, only: [:show, :add_downloadable_material, :add_downloadable_material]

  def index
    add_breadcrumb @course.name if @course
    add_breadcrumb 'lessons', course_lessons_path(@course)
    @lessons = Lesson.where(course_uuid: params[:course_uuid])
  end

  def show
    add_breadcrumb @lesson.course.name if @lesson.course
    add_breadcrumb 'lessons', course_lessons_path(@lesson.course)
    add_breadcrumb @lesson.title, lesson_path(@lesson)
    @add_material_command = CourseManagement::AddDownloadableMaterialToLesson.new
  end

  def new
    add_breadcrumb @course.name if @course
    add_breadcrumb 'lessons', course_lessons_path(@course)
    add_breadcrumb 'new lesson', new_course_lesson_path(@course)
    @create_lesson_cmd = CourseManagement::DraftLesson.new(lesson_uuid: SecureRandom.uuid)
  end

  def create
    @create_lesson_cmd = CourseManagement::DraftLesson.new(lesson_params)
    @create_lesson_cmd.course = @course
    command_bus.(@create_lesson_cmd)
    if @create_lesson_cmd.errors.any?
      render 'new'
    else
      redirect_to course_lessons_path(@course), notice: 'Lesson was successfully created.'
    end
  end

  def add_downloadable_material
    @add_material_command = CourseManagement::AddDownloadableMaterialToLesson.new(add_downloadable_material_params)
    @add_material_command.lesson_uuid = @lesson.uuid
    command_bus.(@add_material_command)
    if @add_material_command.errors.any?
      render 'show'
    else
      redirect_to lesson_path(@lesson), notice: 'Material was successfully added to lesson.'
    end
  rescue CourseManagement::Lesson::IncorrectAttachmentToken
    flash.now[:alert] = 'There was a problem with file submission.'
    render 'show'
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_course
    @course = Course.find(params[:course_uuid]) if params[:course_uuid].present?
  end

  def lesson_params
    params.require(:lesson).permit(:lesson_uuid, :title, :description)
  end

  def add_downloadable_material_params
    params.require(:downloadable_material).permit(:attachment_name, :attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<div class="album py-5">
  <div class="row">
    <% @courses.each do |course| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
            <title><%= course.name %></title>
            <rect width="100%" height="100%" fill="#55595c"/>
            <text x="50%" y="50%" fill="#eceeef" dy=".3em"><%= course.name %></text>
          </svg>
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= link_to 'Show lessons', course_lessons_path(course), class: 'btn btn-sm btn-outline-secondary' %>
              </div>
              <small class="text-muted"><%= pluralize(course.lessons_count, 'lesson') %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'New course', new_course_path, class: 'btn btn-primary' %>
<%= link_to 'Not assgined lessons', course_lessons_path, class: 'btn btn-secondary float-right' %>

app/views/courses/new.html.erb
<%= simple_form_for @create_course_cmd, as: :course, url: courses_path do |f| %>
  <%= f.input :course_uuid, as: :hidden %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit, 'Create new course' %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Courses</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta name="theme-color" content="#563d7c">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
</head>
<body>

<main role="main">
  <div class="container">
    <%= render_breadcrumbs builder: ::BootstrapBreadcrumbsBuilder %>

    <div id="alerts">
      <% flash.each do |name, msg| %>
        <% (msg.is_a?(Array) ? msg : [msg]).each do |single_msg| %>
          <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
            <%= content_tag :div, single_msg.html_safe, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
    </div>

    <%= yield %>
  </div>
</main>
</body>
</html>

app/views/lessons/index.html.erb
<h1 class="mt-5">
  <% if @course %>
    Lessons of <i><%= @course.name %></i> course
  <% else %>
    Lessons not assigned to any course
  <% end %>
</h1>
<% if @lessons.any? %>
  <div class="list-group my-5">
    <% @lessons.each_with_index do |lesson, index| %>
      <%= link_to lesson_path(lesson.uuid), class: 'list-group-item list-group-item-action' do %>
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1"><%= lesson.title %></h5>
          <small><%= "lesson ##{index + 1}" %></small>
        </div>
        <p class="mb-1"><%= lesson.description %></p>
      <% end %>
    <% end %>
  </div>
<% else %>
  <p class="my-5">There are no lessons here</p>
<% end %>
<%= link_to 'New lesson', new_course_lesson_path(@course), class: 'btn btn-primary' %>

app/views/lessons/new.html.erb
  <%= simple_form_for @create_lesson_cmd, as: :lesson, url: course_lessons_path(@course) do |f| %>
    <%= f.input :lesson_uuid, as: :hidden %>
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.button :submit, 'Create new lesson' %>
  <% end %>

app/views/lessons/show.html.erb
<div class="row">
  <div class="col">
    <h1 class="mt-5"><%= @lesson.title %></h1>
    <p><%= @lesson.description %></p>
  </div>
  <div class="col">
    <h2 class="mt-5">Materials to download:</h2>
    <% if @lesson.downloadable_materials.any? %>
      <div class="list-group my-5">
        <% @lesson.downloadable_materials.each do |material| %>
          <%= link_to "<i class='fa fa-download'></i> #{material.attachment_name}".html_safe, rails_blob_path(material.attachment, disposition: 'attachment'), class: 'list-group-item list-group-item-action' %>
        <% end %>
      </div>
    <% else %>
      <p class="my-5">There is nothing to download</p>
    <% end %>

    <%= simple_form_for @add_material_command, as: :downloadable_material, url: add_downloadable_material_lesson_path(@lesson), method: 'put' do |f| %>
      <%= f.input :lesson_uuid, as: :hidden %>
      <%= f.input :attachment_name %>
      <%= f.input :attachment, as: :file, label: false, input_html: {data: {direct_upload_url: '/rails/active_storage/direct_uploads'}} %>
      <%= f.button :submit, 'Import file' %>
    <% end %>
  </div>
</div>